/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    leads: Lead;
    directions: Direction;
    categories: Category;
    products: Product;
    projects: Project;
    documents: Document;
    pages: Page;
    media: Media;
    'product-images': ProductImage;
    files: File;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    leads: LeadsSelect<false> | LeadsSelect<true>;
    directions: DirectionsSelect<false> | DirectionsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'product-images': ProductImagesSelect<false> | ProductImagesSelect<true>;
    files: FilesSelect<false> | FilesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: string;
  number: number;
  type: 'callback' | 'quote' | 'calculation';
  status: 'new' | 'in_progress' | 'done' | 'spam';
  managerComment?: string | null;
  name: string;
  phone: string;
  email?: string | null;
  organization?: string | null;
  inn?: string | null;
  region?: string | null;
  product?: (string | null) | Product;
  direction?: (string | null) | Direction;
  quantity?: number | null;
  message?: string | null;
  sourceUrl?: string | null;
  utm?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  consentAt: string;
  consentVersion: string;
  ip?: string | null;
  userAgent?: string | null;
  dedupeKey?: string | null;
  notifications?: {
    email?: ('pending' | 'sent' | 'failed' | 'skipped') | null;
    telegram?: ('pending' | 'sent' | 'failed' | 'skipped') | null;
    attempts?: number | null;
    lastError?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  title: string;
  /**
   * Заполняется автоматически из названия. Меняйте только при необходимости: старые ссылки перестанут работать.
   */
  slug: string;
  sku: string;
  direction: string | Direction;
  category: string | Category;
  shortDescription?: string | null;
  gallery: (string | ProductImage)[];
  drawing?: (string | null) | ProductImage;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  lengthMm?: number | null;
  widthMm?: number | null;
  heightMm?: number | null;
  weightKg?: number | null;
  materials?:
    | {
        material: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Пример: порошковая окраска по RAL, цвет по выбору
   */
  coating?: string | null;
  productionDaysMin?: number | null;
  productionDaysMax?: number | null;
  warrantyMonths?: number | null;
  okpd2?: string | null;
  inGispRegistry?: boolean | null;
  gispRegistryNumber?: string | null;
  /**
   * Строки создаются из набора характеристик категории при сохранении. Заполните только «Значение».
   */
  attributes?:
    | {
        key?: string | null;
        label?: string | null;
        value?: string | null;
        unit?: string | null;
        id?: string | null;
      }[]
    | null;
  relatedProducts?: (string | Product)[] | null;
  featured?: boolean | null;
  order?: number | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "directions".
 */
export interface Direction {
  id: string;
  title: string;
  /**
   * Заполняется автоматически из названия. Меняйте только при необходимости: старые ссылки перестанут работать.
   */
  slug: string;
  type: 'catalog' | 'service';
  order?: number | null;
  shortDescription: string;
  cover?: (string | null) | Media;
  heroText?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Для страницы «Госзаказчикам». Пример: 31.01.12
   */
  okpd2?: string | null;
  service?: {
    workScope?:
      | {
          item: string;
          id?: string | null;
        }[]
      | null;
    stages?:
      | {
          title: string;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
    objectTypes?:
      | {
          item: string;
          id?: string | null;
        }[]
      | null;
    formHint?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  /**
   * Заполняется автоматически из названия. Меняйте только при необходимости: старые ссылки перестанут работать.
   */
  slug: string;
  direction: string | Direction;
  order?: number | null;
  shortDescription?: string | null;
  cover?: (string | null) | Media;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  okpd2?: string | null;
  /**
   * Эти строки появятся в каждом товаре категории после сохранения черновика
   */
  attributeSet?:
    | {
        key: string;
        label: string;
        unit?: string | null;
        required?: boolean | null;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-images".
 */
export interface ProductImage {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  title: string;
  /**
   * Заполняется автоматически из названия. Меняйте только при необходимости: старые ссылки перестанут работать.
   */
  slug: string;
  year?: number | null;
  city: string;
  customerName?: string | null;
  /**
   * Включайте, только если в договоре нет запрета на публикацию
   */
  showCustomer?: boolean | null;
  /**
   * Можно оставить пустым у черновика, но перед публикацией выберите направление
   */
  directions?: (string | Direction)[] | null;
  products?: (string | Product)[] | null;
  summary: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  cover?: (string | null) | Media;
  gallery?: (string | Media)[] | null;
  featured?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: string;
  title: string;
  docType: 'certificate' | 'declaration' | 'sro' | 'license' | 'registry' | 'letter' | 'catalog' | 'other';
  file: string | File;
  preview?: (string | null) | Media;
  number?: string | null;
  issuedAt?: string | null;
  validUntil?: string | null;
  directions?: (string | Direction)[] | null;
  showOnHome?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "files".
 */
export interface File {
  id: string;
  title: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  slug:
    | 'o-kompanii'
    | 'proizvodstvo'
    | 'goszakazchikam'
    | 'dostavka-i-oplata'
    | 'garantiya'
    | 'politika-konfidencialnosti'
    | 'soglasie-na-obrabotku'
    | 'cookie';
  lead?: string | null;
  cover?: (string | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  gallery?: (string | Media)[] | null;
  /**
   * Пример: 2026-10-01. Меняйте при каждой правке текста согласия
   */
  version?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'leads';
        value: string | Lead;
      } | null)
    | ({
        relationTo: 'directions';
        value: string | Direction;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'documents';
        value: string | Document;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'product-images';
        value: string | ProductImage;
      } | null)
    | ({
        relationTo: 'files';
        value: string | File;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  number?: T;
  type?: T;
  status?: T;
  managerComment?: T;
  name?: T;
  phone?: T;
  email?: T;
  organization?: T;
  inn?: T;
  region?: T;
  product?: T;
  direction?: T;
  quantity?: T;
  message?: T;
  sourceUrl?: T;
  utm?: T;
  consentAt?: T;
  consentVersion?: T;
  ip?: T;
  userAgent?: T;
  dedupeKey?: T;
  notifications?:
    | T
    | {
        email?: T;
        telegram?: T;
        attempts?: T;
        lastError?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "directions_select".
 */
export interface DirectionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  order?: T;
  shortDescription?: T;
  cover?: T;
  heroText?: T;
  description?: T;
  okpd2?: T;
  service?:
    | T
    | {
        workScope?:
          | T
          | {
              item?: T;
              id?: T;
            };
        stages?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
        objectTypes?:
          | T
          | {
              item?: T;
              id?: T;
            };
        formHint?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  direction?: T;
  order?: T;
  shortDescription?: T;
  cover?: T;
  description?: T;
  okpd2?: T;
  attributeSet?:
    | T
    | {
        key?: T;
        label?: T;
        unit?: T;
        required?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  sku?: T;
  direction?: T;
  category?: T;
  shortDescription?: T;
  gallery?: T;
  drawing?: T;
  description?: T;
  lengthMm?: T;
  widthMm?: T;
  heightMm?: T;
  weightKg?: T;
  materials?:
    | T
    | {
        material?: T;
        id?: T;
      };
  coating?: T;
  productionDaysMin?: T;
  productionDaysMax?: T;
  warrantyMonths?: T;
  okpd2?: T;
  inGispRegistry?: T;
  gispRegistryNumber?: T;
  attributes?:
    | T
    | {
        key?: T;
        label?: T;
        value?: T;
        unit?: T;
        id?: T;
      };
  relatedProducts?: T;
  featured?: T;
  order?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  year?: T;
  city?: T;
  customerName?: T;
  showCustomer?: T;
  directions?: T;
  products?: T;
  summary?: T;
  description?: T;
  cover?: T;
  gallery?: T;
  featured?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  docType?: T;
  file?: T;
  preview?: T;
  number?: T;
  issuedAt?: T;
  validUntil?: T;
  directions?: T;
  showOnHome?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  lead?: T;
  cover?: T;
  content?: T;
  gallery?: T;
  version?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-images_select".
 */
export interface ProductImagesSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "files_select".
 */
export interface FilesSelect<T extends boolean = true> {
  title?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  companyName: string;
  tagline?: string | null;
  logo?: (string | null) | Media;
  facts?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Показывается на главной, в карточках и на странице «Гарантия». Писать только здесь.
   */
  warrantyShort?: string | null;
  responseTimePromise?: string | null;
  catalogPdf?: (string | null) | File;
  companyCardFile?: (string | null) | File;
  /**
   * Оставьте пустым, если продукции нет в реестре — блок не будет показан
   */
  gispNote?: string | null;
  phones?:
    | {
        number: string;
        label?: string | null;
        primary?: boolean | null;
        id?: string | null;
      }[]
    | null;
  emails?:
    | {
        email: string;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  telegramUrl?: string | null;
  /**
   * Не рекомендуется: сервис ограничен в РФ. Если пусто — кнопка не показывается.
   */
  whatsappUrl?: string | null;
  workingHours?: string | null;
  productionAddress?: string | null;
  lat?: number | null;
  lng?: number | null;
  legalName?: string | null;
  inn?: string | null;
  kpp?: string | null;
  ogrn?: string | null;
  legalAddress?: string | null;
  bankDetails?: string | null;
  notifyEmails?:
    | {
        email: string;
        id?: string | null;
      }[]
    | null;
  telegramChatIds?:
    | {
        chatId: string;
        id?: string | null;
      }[]
    | null;
  metrikaId?: string | null;
  yandexVerification?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: string;
  heroTitle: string;
  heroSubtitle: string;
  heroImage?: (string | null) | Media;
  audiences?:
    | {
        title: string;
        text: string;
        /**
         * Внутренний путь, например /goszakazchikam
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  productionText?: string | null;
  productionImages?: (string | Media)[] | null;
  steps?:
    | {
        title: string;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  companyName?: T;
  tagline?: T;
  logo?: T;
  facts?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  warrantyShort?: T;
  responseTimePromise?: T;
  catalogPdf?: T;
  companyCardFile?: T;
  gispNote?: T;
  phones?:
    | T
    | {
        number?: T;
        label?: T;
        primary?: T;
        id?: T;
      };
  emails?:
    | T
    | {
        email?: T;
        label?: T;
        id?: T;
      };
  telegramUrl?: T;
  whatsappUrl?: T;
  workingHours?: T;
  productionAddress?: T;
  lat?: T;
  lng?: T;
  legalName?: T;
  inn?: T;
  kpp?: T;
  ogrn?: T;
  legalAddress?: T;
  bankDetails?: T;
  notifyEmails?:
    | T
    | {
        email?: T;
        id?: T;
      };
  telegramChatIds?:
    | T
    | {
        chatId?: T;
        id?: T;
      };
  metrikaId?: T;
  yandexVerification?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  heroImage?: T;
  audiences?:
    | T
    | {
        title?: T;
        text?: T;
        href?: T;
        id?: T;
      };
  productionText?: T;
  productionImages?: T;
  steps?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}